INSERT INTO public.p_attack_skill ("name",description,"type",attack_points,smasher_id) VALUES
	 ('leżing','','brak_typu',9,1),
	 ('atak rurą','','fizyczny',11,1),
	 ('rozgrzane siedzenie','','ognisty',12,1),
	 ('zwarcie','','elektryczny',12,2),
	 ('przegrzanie styków','','ognisty',10,2),
	 ('super wentylator','','powietrzny',8,2),
	 ('smog','','powietrzny',6,3),
	 ('ogień z paszczy','','ognisty',12,3),
	 ('cios ogonem','','fizyczny',12,3),
	 ('wystrzał','','powietrzny',15,4),
	 ('przejechanie','','fizyczny',7,4),
	 ('turbo jazda','','ognisty',12,4),
	 ('jednocalowy cios','','fizyczny',15,5),
	 ('pięści smoka','','ognisty',15,5),
	 ('błyskawiczna podcinka','','elektryczny',10,5),
	 ('wrzący wodospad kawy','','ognisty',15,6),
	 ('deszcz fusów','','powietrzny',10,6),
	 ('RuntimeException','','elektryczny',12,6),
	 ('rzut cegłą','','powietrzny',10,7),
	 ('dym','','elektryczny',8,7),
	 ('low king','','fizyczny',11,7);
